scrape_configs:


- job_name: 'cadvisor'

  # discover cadvisor instances using node's docker socket
  dockerswarm_sd_configs:
  - host: unix:///var/run/docker.sock
    role: tasks

  relabel_configs:


  # only match running tasks
  - source_labels: [__meta_dockerswarm_task_desired_state]
    regex: running
    action: keep

  # only match containers with 'prometheus_job=cadvisor' label
  - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
    regex: cadvisor
    action: keep

  # replace port with cadvisor port
  - source_labels: [__address__]
    target_label: __address__
    regex: (.*):.*
    replacement: ${1}:8000