scrape_configs:

  # Create a job for cadvisor instances.
  - job_name: 'cadvisor'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # Fetch metrics on port 8080.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:8080
      # Set hostname as instance label.
      - source_labels: [__met_dockerswarm_node_hostname]
        target_label: instance